name: Push

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
        env:
          debug: true
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: x86_64-unknown-linux-gnu
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Setup LLVM & Clang
        id: clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: 17
          directory: ${{ runner.temp }}/llvm-17
      - name: Configure Clang
        if: "!contains(matrix.os, 'windows')"
        run: |
          echo "LIBCLANG_PATH=${{ runner.temp }}/llvm-17/lib" >> $GITHUB_ENV
          echo "LLVM_VERSION=${{ steps.clang.outputs.version }}" >> $GITHUB_ENV
          echo "LLVM_CONFIG_PATH=${{ runner.temp }}/llvm-17/bin/llvm-config" >> $GITHUB_ENV
      - name: Build
        run: cargo build --locked -v
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: libext_itertools_debug
          path: target/debug/libext_itertools*

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Install Rust
  #       uses: dtolnay/rust-toolchain@stable
  #     - name: Install llvm-cov
  #       uses: taiki-e/install-action@cargo-llvm-cov
  #     - name: Cache
  #       uses: Swatinem/rust-cache@v2
  #     - name: Generate code coverage
  #       run: cargo llvm-cov --lcov --output-path lcov.info
  #       env:
  #         OUT_DIR: target
  #     - name: Upload coverage reports to Codecov
  #       uses: codecov/codecov-action@v3
  #       with:
  #         files: lcov.info
  #         fail_ci_if_error: true
  #       env:
  #         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check typos
        uses: crate-ci/typos@master
      - name: Validate commit messages
        run: |
          git show-ref
          curl -sSfL https://github.com/convco/convco/releases/latest/download/convco-ubuntu.zip | zcat > convco
          chmod +x convco
          ./convco check refs/remotes/origin/master..HEAD
          rm convco
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
      - name: Check code formatting
        run: cargo fmt --all -- --check
      - name: Check lints
        run: cargo clippy --all-targets --all-features --target x86_64-unknown-linux-gnu -- -W clippy::pedantic -Dwarnings
      - name: Run cargo-audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Composer install
      uses: php-actions/composer@v6
    - name: phpunit
      run: vendor/bin/phpunit --no-coverage

  static-analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Composer install
      uses: php-actions/composer@v6
    - name: phpstan
      uses: php-actions/phpstan@v3
      with:
        path: src/
        level: max

  code-sniffer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Composer install
        uses: php-actions/composer@v6
      - name: PHP Code Sniffer
        uses: php-actions/phpcs@v1
        with:
          standard: phpcs.xml
