name: Push

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Composer install
      uses: php-actions/composer@v6
    - name: phpunit
      uses: php-actions/phpunit@v3
      with:
        args: "test"

  static-analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Composer install
      uses: php-actions/composer@v6
    - name: phpstan
      uses: php-actions/phpstan@v3
      with:
        path: src/

  code-sniffer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Composer install
        uses: php-actions/composer@v6
      - name: PHP Code Sniffer
        uses: php-actions/phpcs@v1
        with:
          path: src/
